### Analyze the search complexity as a function of domain size, search algorithm, and heuristic

- The following table includes data for all search & heuristic combinations for air cargo problems 1 and 2:
  <table>
    <thead>
        <tr>
            <th>Air Cargo Problem</th>
            <th>Actions</th>
            <th>Search Function</th>
            <th>New Nodes</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>1</td>
            <td>20</td>
            <td>1</td>
            <td>178</td>
        </tr>
        <tr>
            <td>1</td>
            <td>20</td>
            <td>2</td>
            <td>84</td>
        </tr>
        <tr>
            <td>1</td>
            <td>20</td>
            <td>3</td>
            <td>240</td>
        </tr>
        <tr>
            <td>1</td>
            <td>20</td>
            <td>4</td>
            <td>29</td>
        </tr>
        <tr>
            <td>1</td>
            <td>20</td>
            <td>5</td>
            <td>28</td>
        </tr>
        <tr>
            <td>1</td>
            <td>20</td>
            <td>6</td>
            <td>24</td>
        </tr>
        <tr>
            <td>1</td>
            <td>20</td>
            <td>7</td>
            <td>190</td>
        </tr>
        <tr>
            <td>1</td>
            <td>20</td>
            <td>8</td>
            <td>206</td>
        </tr>
        <tr>
            <td>1</td>
            <td>20</td>
            <td>9</td>
            <td>122</td>
        </tr>
        <tr>
            <td>1</td>
            <td>20</td>
            <td>10</td>
            <td>180</td>
        </tr>
        <tr>
            <td>1</td>
            <td>20</td>
            <td>11</td>
            <td>226</td>
        </tr>
        <tr>
            <td>2</td>
            <td>72</td>
            <td>1</td>
            <td>30503</td>
        </tr>
        <tr>
            <td>2</td>
            <td>72</td>
            <td>2</td>
            <td>5602</td>
        </tr>
        <tr>
            <td>2</td>
            <td>72</td>
            <td>3</td>
            <td>46618</td>
        </tr>
        <tr>
            <td>2</td>
            <td>72</td>
            <td>4</td>
            <td>170</td>
        </tr>
        <tr>
            <td>2</td>
            <td>72</td>
            <td>5</td>
            <td>86</td>
        </tr>
        <tr>
            <td>2</td>
            <td>72</td>
            <td>6</td>
            <td>249</td>
        </tr>
        <tr>
            <td>2</td>
            <td>72</td>
            <td>7</td>
            <td>84</td>
        </tr>
        <tr>
            <td>2</td>
            <td>72</td>
            <td>8</td>
            <td>22522</td>
        </tr>
        <tr>
            <td>2</td>
            <td>72</td>
            <td>9</td>
            <td>3426</td>
        </tr>
        <tr>
            <td>2</td>
            <td>72</td>
            <td>10</td>
            <td>26594</td>
        </tr>
        <tr>
            <td>2</td>
            <td>72</td>
            <td>11</td>
            <td>9605</td>
        </tr></tbody></table>
- The following table includes data for one uniformed search, two heuristics with greedy best first serach, and two heuristics with A* on air cargo problem 3 and 4:
  <table>
    <thead>
        <tr>
            <th>Air Cargo Problem</th>
            <th>Actions</th>
            <th>Search Function</th>
            <th>New Nodes</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>3</td>
            <td>20</td>
            <td>1</td>
            <td>178</td>
        </tr>
        <tr>
            <td>3</td>
            <td>20</td>
            <td>4</td>
            <td>29</td>
        </tr>
        <tr>
        <tr>
            <td>3</td>
            <td>20</td>
            <td>8</td>
            <td>206</td>
        </tr>
        <tr>
            <td>4</td>
            <td>72</td>
            <td>1</td>
            <td>30503</td>
        </tr>
        <tr>
            <td>4</td>
            <td>72</td>
            <td>4</td>
            <td>170</td>
        </tr>
        <tr>
            <td>4</td>
            <td>72</td>
            <td>8</td>
            <td>5602</td>
        </tr></tbody></table>