### Analyze the search complexity as a function of domain size, search algorithm, and heuristic

- The following table includes data for all search & heuristic combinations for air cargo problems 1 and 2:
  <table>
    <thead>
        <tr>
            <th>Air Cargo Problem</th>
            <th>Actions</th>
            <th>Search Function</th>
            <th>New Nodes</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>1</td>
            <td>20</td>
            <td>1</td>
            <td>178</td>
        </tr>
        <tr>
            <td>1</td>
            <td>20</td>
            <td>2</td>
            <td>84</td>
        </tr>
        <tr>
            <td>1</td>
            <td>20</td>
            <td>3</td>
            <td>240</td>
        </tr>
        <tr>
            <td>1</td>
            <td>20</td>
            <td>4</td>
            <td>29</td>
        </tr>
        <tr>
            <td>1</td>
            <td>20</td>
            <td>5</td>
            <td>28</td>
        </tr>
        <tr>
            <td>1</td>
            <td>20</td>
            <td>6</td>
            <td>24</td>
        </tr>
        <tr>
            <td>1</td>
            <td>20</td>
            <td>7</td>
            <td>28</td>
        </tr>
        <tr>
            <td>1</td>
            <td>20</td>
            <td>8</td>
            <td>206</td>
        </tr>
        <tr>
            <td>1</td>
            <td>20</td>
            <td>9</td>
            <td>122</td>
        </tr>
        <tr>
            <td>1</td>
            <td>20</td>
            <td>10</td>
            <td>180</td>
        </tr>
        <tr>
            <td>1</td>
            <td>20</td>
            <td>11</td>
            <td>138</td>
        </tr>
        <tr>
            <td>2</td>
            <td>72</td>
            <td>1</td>
            <td>30503</td>
        </tr>
        <tr>
            <td>2</td>
            <td>72</td>
            <td>2</td>
            <td>5602</td>
        </tr>
        <tr>
            <td>2</td>
            <td>72</td>
            <td>3</td>
            <td>46618</td>
        </tr>
        <tr>
            <td>2</td>
            <td>72</td>
            <td>4</td>
            <td>170</td>
        </tr>
        <tr>
            <td>2</td>
            <td>72</td>
            <td>5</td>
            <td>86</td>
        </tr>
        <tr>
            <td>2</td>
            <td>72</td>
            <td>6</td>
            <td>249</td>
        </tr>
        <tr>
            <td>2</td>
            <td>72</td>
            <td>7</td>
            <td>84</td>
        </tr>
        <tr>
            <td>2</td>
            <td>72</td>
            <td>8</td>
            <td>22522</td>
        </tr>
        <tr>
            <td>2</td>
            <td>72</td>
            <td>9</td>
            <td>3426</td>
        </tr>
        <tr>
            <td>2</td>
            <td>72</td>
            <td>10</td>
            <td>26594</td>
        </tr>
        <tr>
            <td>2</td>
            <td>72</td>
            <td>11</td>
            <td>9605</td>
        </tr></tbody></table>
- The following table includes data for one uniformed search, two heuristics with greedy best first search, and two heuristics with A* on air cargo problems 3 and 4:
  <table>
    <thead>
        <tr>
            <th>Air Cargo Problem</th>
            <th>Actions</th>
            <th>Search Function</th>
            <th>New Nodes</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>3</td>
            <td>88</td>
            <td>1</td>
            <td>129625</td>
        </tr>
        <tr>
            <td>3</td>
            <td>88</td>
            <td>4</td>
            <td>230</td>
        </tr>
        <tr>
        <tr>
            <td>3</td>
            <td>88</td>
            <td>5</td>
            <td>126</td>
        </tr>
        <tr>
            <td>3</td>
            <td>88</td>
            <td>8</td>
            <td>65711</td>
        </tr>
        <tr>
        <tr>
            <td>3</td>
            <td>88</td>
            <td>9</td>
            <td>3403</td>
        </tr>
        <tr>
            <td>4</td>
            <td>104</td>
            <td>1</td>
            <td>944130</td>
        </tr>
        <tr>
            <td>4</td>
            <td>104</td>
            <td>4</td>
            <td>280</td>
        </tr>
        <tr>
            <td>4</td>
            <td>104</td>
            <td>5</td>
            <td>165</td>
        </tr>
        <tr>
            <td>4</td>
            <td>104</td>
            <td>8</td>
            <td>328509</td>
        </tr>
        <tr>
            <td>4</td>
            <td>104</td>
            <td>9</td>
            <td>12210</td>
        </tr></tbody></table>
- Regarding the growth trends as the problem size increases,

### Analyze the search time as a function of domain size, search algorithm, and heuristic

- The following table includes data for all search & heuristic combinations for air cargo problems 1 and 2:
  <table>
    <thead>
        <tr>
            <th>Air Cargo Problem</th>
            <th>Actions</th>
            <th>Search Function</th>
            <th>Search Time</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>1</td>
            <td>20</td>
            <td>1</td>
            <td>0.005738312</td>
        </tr>
        <tr>
            <td>1</td>
            <td>20</td>
            <td>2</td>
            <td>0.003031437</td>
        </tr>
        <tr>
            <td>1</td>
            <td>20</td>
            <td>3</td>
            <td>0.008646773</td>
        </tr>
        <tr>
            <td>1</td>
            <td>20</td>
            <td>4</td>
            <td>0.001422161</td>
        </tr>
        <tr>
            <td>1</td>
            <td>20</td>
            <td>5</td>
            <td>0.430203578</td>
        </tr>
        <tr>
            <td>1</td>
            <td>20</td>
            <td>6</td>
            <td>0.123274573</td>
        </tr>
        <tr>
            <td>1</td>
            <td>20</td>
            <td>7</td>
            <td>1.154152003</td>
        </tr>
        <tr>
            <td>1</td>
            <td>20</td>
            <td>8</td>
            <td>0.008778578</td>
        </tr>
        <tr>
            <td>1</td>
            <td>20</td>
            <td>9</td>
            <td>1.096785234</td>
        </tr>
        <tr>
            <td>1</td>
            <td>20</td>
            <td>10</td>
            <td>0.446812224</td>
        </tr>
        <tr>
            <td>1</td>
            <td>20</td>
            <td>11</td>
            <td>3.002503949</td>
        </tr>
        <tr>
            <td>2</td>
            <td>72</td>
            <td>1</td>
            <td>1.793659079</td>
        </tr>
        <tr>
            <td>2</td>
            <td>72</td>
            <td>2</td>
            <td>2.714538505</td>
        </tr>
        <tr>
            <td>2</td>
            <td>72</td>
            <td>3</td>
            <td>3.067347889</td>
        </tr>
        <tr>
            <td>2</td>
            <td>72</td>
            <td>4</td>
            <td>0.017521590</td>
        </tr>
        <tr>
            <td>2</td>
            <td>72</td>
            <td>5</td>
            <td>10.322775617</td>
        </tr>
        <tr>
            <td>2</td>
            <td>72</td>
            <td>6</td>
            <td>5.927637818</td>
        </tr>
        <tr>
            <td>2</td>
            <td>72</td>
            <td>7</td>
            <td>25.886673475</td>
        </tr>
        <tr>
            <td>2</td>
            <td>72</td>
            <td>8</td>
            <td>2.055049125</td>
        </tr>
        <tr>
            <td>2</td>
            <td>72</td>
            <td>9</td>
            <td>260.652598607</td>
        </tr>
        <tr>
            <td>2</td>
            <td>72</td>
            <td>10</td>
            <td>602.945406510</td>
        </tr>
        <tr>
            <td>2</td>
            <td>72</td>
            <td>11</td>
            <td>1962.084911764</td>
        </tr></tbody></table>
- The following table includes data for one uniformed search, two heuristics with greedy best first search, and two heuristics with A* on air cargo problems 3 and 4:
  <table>
    <thead>
        <tr>
            <th>Air Cargo Problem</th>
            <th>Actions</th>
            <th>Search Function</th>
            <th>New Nodes</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>3</td>
            <td>88</td>
            <td>1</td>
            <td>9.726209561</td>
        </tr>
        <tr>
            <td>3</td>
            <td>88</td>
            <td>4</td>
            <td>0.034026403</td>
        </tr>
        <tr>
        <tr>
            <td>3</td>
            <td>88</td>
            <td>5</td>
            <td>23.441392788</td>
        </tr>
        <tr>
            <td>3</td>
            <td>88</td>
            <td>8</td>
            <td>7.875705338</td>
        </tr>
        <tr>
        <tr>
            <td>3</td>
            <td>88</td>
            <td>9</td>
            <td>426.632465442</td>
        </tr>
        <tr>
            <td>4</td>
            <td>104</td>
            <td>1</td>
            <td>88.426900362</td>
        </tr>
        <tr>
            <td>4</td>
            <td>104</td>
            <td>4</td>
            <td>0.055148840</td>
        </tr>
        <tr>
            <td>4</td>
            <td>104</td>
            <td>5</td>
            <td>42.506554062</td>
        </tr>
        <tr>
            <td>4</td>
            <td>104</td>
            <td>8</td>
            <td>51.476212157</td>
        </tr>
        <tr>
            <td>4</td>
            <td>104</td>
            <td>9</td>
            <td>2389.225633150</td>
        </tr></tbody></table>
- Regarding the growth trends as the problem size increases,

### Analyze the optimality of solution as a function of domain size, search algorithm, and heuristic

- The following table includes data for all search & heuristic combinations for air cargo problems 1 and 2:
  <table>
    <thead>
        <tr>
            <th>Air Cargo Problem</th>
            <th>Actions</th>
            <th>Search Function</th>
            <th>Plan Length</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>1</td>
            <td>20</td>
            <td>1</td>
            <td>6</td>
        </tr>
        <tr>
            <td>1</td>
            <td>20</td>
            <td>2</td>
            <td>20</td>
        </tr>
        <tr>
            <td>1</td>
            <td>20</td>
            <td>3</td>
            <td>6</td>
        </tr>
        <tr>
            <td>1</td>
            <td>20</td>
            <td>4</td>
            <td>6</td>
        </tr>
        <tr>
            <td>1</td>
            <td>20</td>
            <td>5</td>
            <td>6</td>
        </tr>
        <tr>
            <td>1</td>
            <td>20</td>
            <td>6</td>
            <td>6</td>
        </tr>
        <tr>
            <td>1</td>
            <td>20</td>
            <td>7</td>
            <td>6</td>
        </tr>
        <tr>
            <td>1</td>
            <td>20</td>
            <td>8</td>
            <td>6</td>
        </tr>
        <tr>
            <td>1</td>
            <td>20</td>
            <td>9</td>
            <td>6</td>
        </tr>
        <tr>
            <td>1</td>
            <td>20</td>
            <td>10</td>
            <td>6</td>
        </tr>
        <tr>
            <td>1</td>
            <td>20</td>
            <td>11</td>
            <td>6</td>
        </tr>
        <tr>
            <td>2</td>
            <td>72</td>
            <td>1</td>
            <td>9</td>
        </tr>
        <tr>
            <td>2</td>
            <td>72</td>
            <td>2</td>
            <td>619</td>
        </tr>
        <tr>
            <td>2</td>
            <td>72</td>
            <td>3</td>
            <td>9</td>
        </tr>
        <tr>
            <td>2</td>
            <td>72</td>
            <td>4</td>
            <td>9</td>
        </tr>
        <tr>
            <td>2</td>
            <td>72</td>
            <td>5</td>
            <td>9</td>
        </tr>
        <tr>
            <td>2</td>
            <td>72</td>
            <td>6</td>
            <td>9</td>
        </tr>
        <tr>
            <td>2</td>
            <td>72</td>
            <td>7</td>
            <td>9</td>
        </tr>
        <tr>
            <td>2</td>
            <td>72</td>
            <td>8</td>
            <td>9</td>
        </tr>
        <tr>
            <td>2</td>
            <td>72</td>
            <td>9</td>
            <td>9</td>
        </tr>
        <tr>
            <td>2</td>
            <td>72</td>
            <td>10</td>
            <td>9</td>
        </tr>
        <tr>
            <td>2</td>
            <td>72</td>
            <td>11</td>
            <td>9</td>
        </tr></tbody></table>
- The following table includes data for one uniformed search, two heuristics with greedy best first search, and two heuristics with A* on air cargo problems 3 and 4:
  <table>
    <thead>
        <tr>
            <th>Air Cargo Problem</th>
            <th>Actions</th>
            <th>Search Function</th>
            <th>New Nodes</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>3</td>
            <td>88</td>
            <td>1</td>
            <td>12</td>
        </tr>
        <tr>
            <td>3</td>
            <td>88</td>
            <td>4</td>
            <td>15</td>
        </tr>
        <tr>
        <tr>
            <td>3</td>
            <td>88</td>
            <td>5</td>
            <td>14</td>
        </tr>
        <tr>
            <td>3</td>
            <td>88</td>
            <td>8</td>
            <td>12</td>
        </tr>
        <tr>
        <tr>
            <td>3</td>
            <td>88</td>
            <td>9</td>
            <td>12</td>
        </tr>
        <tr>
            <td>4</td>
            <td>104</td>
            <td>1</td>
            <td>14</td>
        </tr>
        <tr>
            <td>4</td>
            <td>104</td>
            <td>4</td>
            <td>18</td>
        </tr>
        <tr>
            <td>4</td>
            <td>104</td>
            <td>5</td>
            <td>17</td>
        </tr>
        <tr>
            <td>4</td>
            <td>104</td>
            <td>8</td>
            <td>14</td>
        </tr>
        <tr>
            <td>4</td>
            <td>104</td>
            <td>9</td>
            <td>15</td>
        </tr></tbody></table>

### Answer all required questions

-